name: Deploy API to Render

on:
  push:
    branches:
      - render-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Render API Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_API"
        env:
          RENDER_DEPLOY_HOOK_API: ${{ secrets.RENDER_DEPLOY_HOOK_API }}
