name: Deploy Web Apps to Vercel

on:
  push:
    branches:
      - vercel-web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Pull Vercel Project Settings
        run: pnpm dlx vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Generate Vercel Build Output
        run: pnpm dlx vercel build --prod
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}

      - name: Deploy to Vercel Production
        run: pnpm dlx vercel deploy --yes --prebuilt --target=production --token=${{ secrets.VERCEL_TOKEN }}
